/**
 * Curated answer list — every word here is well-known enough that players won't
 * feel cheated. Swap this array for the full NYT list (2309 words) before shipping.
 *
 * Words of all supported lengths (3–8) live in this single flat array.
 * useWordle filters by the active wordLength at runtime.
 *
 * Daily answer selection: index = days elapsed since EPOCH_DATE (see useWordle.ts)
 */
export const ANSWERS: string[] = [
  // ── 3-letter ──────────────────────────────────────────────────────────────
  'ace', 'age', 'aid', 'aim', 'air', 'art', 'ask', 'bad', 'bag', 'ban',
  'bar', 'bat', 'bay', 'bed', 'big', 'bit', 'bow', 'box', 'boy', 'bug',
  'bun', 'bus', 'buy', 'can', 'cap', 'car', 'cat', 'cup', 'cut', 'day',
  'dig', 'dog', 'dot', 'ear', 'eat', 'egg', 'end', 'eve', 'eye', 'fan',
  'far', 'fat', 'few', 'fit', 'fix', 'fly', 'fog', 'fun', 'fur', 'gap',
  'gas', 'gem', 'got', 'gum', 'gun', 'gut', 'guy', 'had', 'ham', 'hat',
  'hay', 'hem', 'hip', 'hit', 'hot', 'hug', 'hut', 'ice', 'ill', 'ivy',
  'jam', 'jar', 'jaw', 'jet', 'joy', 'lab', 'law', 'leg', 'lid', 'lip',
  'lit', 'log', 'lot', 'low', 'mad', 'man', 'map', 'mat', 'men', 'mob',
  'mud', 'mug', 'nap', 'net', 'new', 'nod', 'nut', 'oak', 'oil', 'old',
  'one', 'ore', 'out', 'owl', 'own', 'pad', 'pan', 'par', 'pat', 'paw',
  'pay', 'pen', 'pet', 'pig', 'pin', 'pit', 'pod', 'pop', 'pot', 'pub',
  'pun', 'put', 'rag', 'ran', 'rat', 'raw', 'ray', 'red', 'rib', 'rid',
  'rim', 'rip', 'rot', 'row', 'rug', 'rum', 'run', 'rut', 'rye', 'sad',
  'sap', 'sat', 'saw', 'say', 'sea', 'set', 'sew', 'shy', 'sin', 'sip',
  'sit', 'six', 'sky', 'sob', 'son', 'sow', 'sun', 'tab', 'tan', 'tap',
  'tar', 'tax', 'tea', 'ten', 'tie', 'tin', 'tip', 'toe', 'ton', 'top',
  'toy', 'tug', 'two', 'use', 'van', 'vet', 'vow', 'war', 'wax', 'way',
  'web', 'wed', 'wet', 'win', 'wit', 'woe', 'won', 'yew', 'you', 'zip',

  // ── 4-letter ──────────────────────────────────────────────────────────────
  'able', 'ache', 'acid', 'acre', 'arch', 'area', 'army', 'atom', 'aunt',
  'bake', 'ball', 'band', 'bank', 'bare', 'bark', 'barn', 'base', 'bath',
  'bear', 'beat', 'beer', 'bell', 'belt', 'bill', 'bird', 'bite', 'bold',
  'bolt', 'bond', 'bone', 'book', 'boom', 'boot', 'bore', 'boss', 'bowl',
  'cage', 'cake', 'call', 'calm', 'came', 'camp', 'card', 'care', 'cart',
  'case', 'cash', 'cast', 'cave', 'cell', 'chip', 'chop', 'city', 'clip',
  'club', 'clue', 'coat', 'code', 'coil', 'coin', 'cold', 'cone', 'cool',
  'cope', 'cord', 'core', 'corn', 'cost', 'crew', 'crop', 'cube', 'curl',
  'dare', 'dark', 'data', 'dawn', 'dead', 'deal', 'dear', 'debt', 'deck',
  'deep', 'deny', 'desk', 'diet', 'dirt', 'disk', 'dock', 'dome', 'door',
  'dose', 'dove', 'down', 'draw', 'drip', 'drop', 'drum', 'duck', 'dusk',
  'dust', 'each', 'ease', 'east', 'edge', 'emit', 'even', 'evil', 'exam',
  'face', 'fact', 'fade', 'fair', 'fall', 'fame', 'farm', 'fast', 'fate',
  'fear', 'feel', 'feet', 'fell', 'felt', 'fill', 'film', 'find', 'fine',
  'fire', 'firm', 'fish', 'fist', 'flag', 'flat', 'flaw', 'flew', 'flip',
  'flow', 'foam', 'fold', 'fond', 'foot', 'ford', 'fork', 'form', 'fort',
  'four', 'free', 'frog', 'full', 'fund', 'fuse', 'gale', 'game', 'gang',
  'gear', 'gill', 'glow', 'glue', 'goat', 'gold', 'good', 'gown', 'grab',
  'grim', 'grin', 'grip', 'grit', 'grow', 'gulf', 'gull', 'gust', 'hack',
  'hail', 'hall', 'halt', 'hang', 'hard', 'hare', 'harm', 'harp', 'hash',
  'haul', 'hawk', 'head', 'heal', 'heap', 'heat', 'heel', 'herd', 'here',
  'hike', 'hill', 'hint', 'hire', 'hive', 'hole', 'home', 'hook', 'hope',
  'horn', 'hunt', 'hymn', 'idea', 'inch', 'iron', 'isle', 'jade', 'jail',
  'joke', 'jolt', 'jump', 'junk', 'jury', 'just', 'keen', 'keep', 'kill',
  'kind', 'king', 'kiss', 'knot', 'lack', 'lake', 'land', 'lane', 'lead',
  'leaf', 'lean', 'leap', 'left', 'lend', 'lens', 'lime', 'link', 'lion',
  'lure', 'mail', 'main', 'make', 'mark', 'mass', 'mast', 'meal', 'mean',
  'meet', 'melt', 'memo', 'mere', 'mild', 'mile', 'mill', 'mind', 'mint',
  'miss', 'moan', 'mode', 'mole', 'monk', 'moon', 'more', 'moss', 'moth',
  'much', 'must', 'myth', 'nail', 'name', 'neck', 'need', 'nest', 'news',
  'next', 'nice', 'nine', 'node', 'none', 'noon', 'norm', 'nose', 'note',
  'noun', 'once', 'only', 'open', 'oral', 'over', 'pace', 'pact', 'page',
  'pair', 'pale', 'palm', 'pang', 'park', 'part', 'pass', 'past', 'path',
  'peak', 'pear', 'peel', 'pick', 'pier', 'pile', 'pine', 'pink', 'pipe',
  'plan', 'play', 'ploy', 'plug', 'poem', 'pole', 'poll', 'pond', 'pool',
  'port', 'pose', 'pray', 'prey', 'prop', 'pure', 'push', 'race', 'rage',
  'rain', 'rake', 'ramp', 'rank', 'rare', 'rash', 'read', 'real', 'rein',
  'rent', 'rest', 'rice', 'rich', 'ride', 'ring', 'riot', 'rise', 'risk',
  'roam', 'road', 'roar', 'robe', 'rock', 'role', 'roll', 'roof', 'rope',
  'rose', 'rule', 'rush', 'rust', 'safe', 'sage', 'sail', 'salt', 'same',
  'sand', 'sane', 'save', 'seal', 'seam', 'seat', 'seed', 'seem', 'self',
  'send', 'shin', 'ship', 'shoe', 'shop', 'show', 'silk', 'sing', 'site',
  'size', 'skin', 'slab', 'slam', 'slim', 'slip', 'slow', 'snap', 'snow',
  'soap', 'sock', 'soft', 'soil', 'sold', 'sole', 'song', 'soon', 'sore',
  'sort', 'soul', 'soup', 'sour', 'span', 'spin', 'spot', 'spur', 'star',
  'stem', 'step', 'stew', 'stop', 'suit', 'tail', 'tale', 'tall', 'tame',
  'task', 'teak', 'teal', 'team', 'tear', 'tell', 'term', 'test', 'them',
  'then', 'tilt', 'time', 'toad', 'told', 'toll', 'tomb', 'tone', 'tool',
  'tore', 'torn', 'toss', 'tour', 'town', 'trap', 'tray', 'tree', 'trek',
  'trim', 'trio', 'trip', 'true', 'tuck', 'tune', 'twig', 'type', 'unit',
  'urge', 'vain', 'vale', 'vane', 'vase', 'vast', 'veil', 'vine', 'void',
  'wade', 'wait', 'wake', 'walk', 'wall', 'want', 'ward', 'warm', 'wash',
  'wave', 'weak', 'weep', 'well', 'west', 'wide', 'wild', 'will', 'wind',
  'wine', 'wing', 'wire', 'wish', 'wolf', 'wood', 'word', 'work', 'wrap',
  'wren', 'yard', 'yarn', 'yawn', 'year', 'zero', 'zone', 'zoom',

  // ── 6-letter ──────────────────────────────────────────────────────────────
  'absent', 'accept', 'action', 'afraid', 'agency', 'almost', 'always',
  'animal', 'answer', 'anyone', 'around', 'arrive', 'basket', 'battle',
  'beauty', 'better', 'beyond', 'bottle', 'bought', 'branch', 'bridge',
  'bright', 'broken', 'butter', 'button', 'camera', 'castle', 'caught',
  'center', 'change', 'choice', 'chrome', 'circle', 'clever', 'closed',
  'coffee', 'coming', 'common', 'copper', 'corner', 'cotton', 'couple',
  'course', 'create', 'credit', 'custom', 'damage', 'danger', 'dealer',
  'design', 'dinner', 'direct', 'doctor', 'dollar', 'double', 'dragon',
  'driver', 'during', 'easier', 'effort', 'empire', 'energy', 'engine',
  'enough', 'escape', 'evolve', 'expert', 'famine', 'father', 'figure',
  'finger', 'finish', 'flavor', 'flower', 'flying', 'follow', 'forest',
  'formal', 'foster', 'frozen', 'future', 'garden', 'gentle', 'global',
  'golden', 'ground', 'growth', 'happen', 'hidden', 'honest', 'hunger',
  'hunter', 'impact', 'island', 'jungle', 'junior', 'keeper', 'launch',
  'leader', 'length', 'letter', 'little', 'lonely', 'manage', 'market',
  'master', 'matter', 'midday', 'minute', 'mirror', 'mobile', 'modern',
  'monkey', 'mother', 'motion', 'muscle', 'nation', 'nature', 'nearly',
  'needle', 'nephew', 'number', 'object', 'origin', 'output', 'parent',
  'pardon', 'people', 'pepper', 'pillar', 'pirate', 'planet', 'pocket',
  'police', 'pretty', 'prison', 'proven', 'public', 'purple', 'rabbit',
  'racing', 'reason', 'recent', 'record', 'remain', 'remind', 'repair',
  'report', 'rescue', 'return', 'rocket', 'rubber', 'safely', 'sailor',
  'sample', 'savage', 'secret', 'select', 'senior', 'settle', 'signal',
  'silver', 'simple', 'single', 'sister', 'slowly', 'social', 'speech',
  'spider', 'spirit', 'spread', 'spring', 'square', 'stable', 'stream',
  'street', 'strong', 'struck', 'studio', 'sudden', 'summer', 'supply',
  'surely', 'symbol', 'system', 'taking', 'talent', 'target', 'tender',
  'ticket', 'timber', 'tongue', 'travel', 'treaty', 'tunnel', 'turtle',
  'twelve', 'unfold', 'unique', 'unless', 'unlock', 'update', 'useful',
  'valley', 'vanish', 'velvet', 'virtue', 'vision', 'wallet', 'wealth',
  'winter', 'wisdom', 'within', 'wonder', 'worker', 'writer', 'yellow',
  'zipper',

  // ── 7-letter ──────────────────────────────────────────────────────────────
  'absolve', 'achieve', 'advance', 'airport', 'balance', 'believe', 'beneath',
  'between', 'brother', 'cabinet', 'captain', 'certain', 'chapter', 'charity',
  'college', 'combine', 'comfort', 'command', 'company', 'compare', 'complex',
  'concern', 'conduct', 'confirm', 'connect', 'contain', 'content', 'contest',
  'control', 'convert', 'correct', 'country', 'courage', 'culture', 'current',
  'curtain', 'decided', 'defense', 'deliver', 'destroy', 'develop', 'diamond',
  'disease', 'display', 'distant', 'disturb', 'dolphin', 'example', 'expense',
  'explore', 'express', 'extract', 'factory', 'failure', 'feature', 'feeling',
  'fiction', 'foreign', 'forever', 'freedom', 'general', 'genuine', 'gravity',
  'habitat', 'harvest', 'healthy', 'history', 'horizon', 'however', 'imagine',
  'improve', 'include', 'instead', 'kingdom', 'kitchen', 'knowing', 'learned',
  'leopard', 'liberty', 'machine', 'meaning', 'mention', 'mission', 'mystery',
  'nothing', 'obvious', 'opinion', 'outside', 'patient', 'pattern', 'perfect',
  'perhaps', 'picture', 'plastic', 'plumber', 'popular', 'possess', 'present',
  'problem', 'produce', 'program', 'protect', 'protein', 'provide', 'publish',
  'purpose', 'quantum', 'quickly', 'quietly', 'rainbow', 'reality', 'receive',
  'recover', 'recruit', 'reflect', 'request', 'require', 'respect', 'restore',
  'results', 'revenue', 'section', 'serious', 'service', 'shelter', 'silence',
  'similar', 'society', 'someone', 'species', 'stadium', 'station', 'student',
  'subject', 'success', 'suggest', 'support', 'surface', 'suspect', 'teacher',
  'theater', 'through', 'thunder', 'tonight', 'tourism', 'towards', 'traffic',
  'trouble', 'village', 'warrior', 'weather', 'website', 'weekend', 'whisper',
  'without', 'working', 'worried', 'younger',

  // ── 8-letter ──────────────────────────────────────────────────────────────
  'absolute', 'accident', 'actually', 'alphabet', 'although', 'argument',
  'audience', 'birthday', 'business', 'calendar', 'campaign', 'champion',
  'complete', 'consider', 'continue', 'daughter', 'decision', 'describe',
  'discover', 'distance', 'document', 'dominate', 'download', 'dramatic',
  'educated', 'electric', 'elephant', 'everyone', 'exchange', 'exercise',
  'familiar', 'finished', 'flexible', 'football', 'fraction', 'function',
  'generous', 'grateful', 'guidance', 'hospital', 'humanity', 'increase',
  'infinite', 'innocent', 'internet', 'jealousy', 'judgment', 'keyboard',
  'kindness', 'language', 'laughter', 'learning', 'lifetime', 'marriage',
  'material', 'memories', 'midnight', 'military', 'momentum', 'mountain',
  'movement', 'multiple', 'navigate', 'notebook', 'original', 'overcome',
  'paradise', 'patience', 'peaceful', 'physical', 'platform', 'positive',
  'possible', 'powerful', 'practice', 'precious', 'pressure', 'previous',
  'probably', 'progress', 'purchase', 'quantity', 'question', 'recently',
  'relative', 'research', 'resource', 'response', 'security', 'separate',
  'sequence', 'skeleton', 'solution', 'standard', 'strength', 'struggle',
  'sunshine', 'talented', 'teaching', 'terminal', 'thinking', 'together',
  'tomorrow', 'treasure', 'ultimate', 'umbrella', 'universe', 'unlikely',
  'valuable', 'variable', 'wildlife', 'wireless', 'workshop', 'yearning',
  'about', 'above', 'abuse', 'actor', 'acute', 'admit', 'adopt', 'adult',
  'after', 'again', 'agent', 'agree', 'ahead', 'alarm', 'album', 'alert',
  'alike', 'align', 'alive', 'alley', 'allow', 'alone', 'along', 'alter',
  'angel', 'anger', 'angle', 'angry', 'anime', 'ankle', 'annex', 'annoy',
  'antic', 'anvil', 'apart', 'apple', 'apply', 'arena', 'argue', 'arise',
  'armor', 'aroma', 'arose', 'array', 'arrow', 'aside', 'asset', 'atlas',
  'attic', 'audio', 'audit', 'aunts', 'avail', 'avoid', 'award', 'aware',
  'awful', 'basic', 'basis', 'batch', 'beach', 'began', 'begin', 'being',
  'below', 'bench', 'bible', 'birth', 'black', 'blade', 'blame', 'bland',
  'blank', 'blast', 'blaze', 'bleak', 'blend', 'bless', 'blind', 'block',
  'blood', 'blown', 'board', 'boost', 'booth', 'bound', 'brace', 'brain',
  'brand', 'brave', 'bread', 'break', 'breed', 'brick', 'brief', 'bring',
  'broad', 'broke', 'brook', 'brown', 'brunt', 'brush', 'built', 'burst',
  'buyer', 'byway', 'cabin', 'cache', 'camel', 'caped', 'carry', 'cause',
  'cease', 'chain', 'chair', 'chaos', 'charm', 'chart', 'chase', 'cheap',
  'check', 'cheek', 'chess', 'chest', 'chief', 'child', 'chill', 'choir',
  'civic', 'civil', 'claim', 'clash', 'class', 'clean', 'clear', 'clerk',
  'click', 'cliff', 'climb', 'cling', 'clock', 'clone', 'close', 'cloud',
  'comet', 'comic', 'comma', 'coral', 'could', 'count', 'court', 'cover',
  'craft', 'crane', 'crash', 'craze', 'creak', 'cream', 'creek', 'crime',
  'crisp', 'cross', 'crowd', 'crown', 'crush', 'curve', 'cycle', 'daily',
  'dairy', 'dance', 'datum', 'debut', 'delay', 'delta', 'dense', 'depot',
  'depth', 'derby', 'devil', 'digit', 'diner', 'disco', 'diver', 'dodge',
  'doing', 'doubt', 'dough', 'draft', 'drain', 'drama', 'drank', 'dread',
  'dream', 'dress', 'drink', 'drive', 'drone', 'drove', 'drunk', 'dryer',
  'dying', 'eager', 'early', 'earth', 'eight', 'eject', 'elbow', 'elder',
  'elect', 'elite', 'ember', 'emote', 'empty', 'endow', 'enemy', 'enjoy',
  'enter', 'entry', 'epoch', 'equal', 'error', 'essay', 'ethic', 'event',
  'every', 'exact', 'exist', 'extra', 'fable', 'faced', 'faith', 'false',
  'fancy', 'fault', 'feast', 'fence', 'ferry', 'fetch', 'fever', 'fifth',
  'fifty', 'fight', 'final', 'first', 'fixed', 'fjord', 'flame', 'flash',
  'fleet', 'flesh', 'flick', 'floor', 'flora', 'flour', 'fluid', 'flute',
  'focus', 'foggy', 'folio', 'forge', 'forum', 'found', 'frame', 'frank',
  'fraud', 'fresh', 'frost', 'froze', 'fruit', 'funny', 'genre', 'ghost',
  'giant', 'given', 'gizmo', 'gland', 'glass', 'gleam', 'globe', 'glyph',
  'going', 'grace', 'grade', 'grain', 'grand', 'grant', 'grape', 'grasp',
  'grass', 'grave', 'great', 'green', 'greet', 'grief', 'grind', 'groan',
  'gross', 'group', 'grove', 'grown', 'guard', 'guess', 'guest', 'guide',
  'guild', 'guile', 'guilt', 'guise', 'gusto', 'habit', 'happy', 'harsh',
  'heart', 'heavy', 'herbs', 'hinge', 'hippo', 'hoist', 'honey', 'honor',
  'horse', 'hotel', 'house', 'human', 'humid', 'humor', 'hurry', 'hyper',
  'ideal', 'image', 'imply', 'inbox', 'index', 'infer', 'inner', 'input',
  'inter', 'intro', 'inure', 'irony', 'issue', 'ivory', 'japan', 'jewel',
  'joust', 'juice', 'juicy', 'jumbo', 'kayak', 'knack', 'kneel', 'knife',
  'knock', 'known', 'label', 'large', 'laser', 'later', 'latte', 'laugh',
  'layer', 'learn', 'leave', 'ledge', 'legal', 'level', 'light', 'limit',
  'linen', 'liner', 'liver', 'lodge', 'logic', 'login', 'loose', 'lover',
  'lower', 'lucky', 'lumen', 'lunar', 'lusty', 'lymph', 'lyric', 'macro',
  'magic', 'magma', 'major', 'maker', 'manor', 'maple', 'march', 'marsh',
  'media', 'melee', 'mercy', 'merge', 'merit', 'merry', 'metal', 'might',
  'miner', 'minor', 'minus', 'mirth', 'mixed', 'mocha', 'model', 'money',
  'month', 'moral', 'motel', 'motor', 'mount', 'mouse', 'moved', 'movie',
  'muddy', 'music', 'naive', 'nasty', 'naval', 'nerve', 'never', 'night',
  'ninja', 'noise', 'north', 'noted', 'novel', 'nudge', 'nurse', 'nymph',
  'occur', 'ocean', 'offer', 'often', 'olive', 'onset', 'opera', 'optic',
  'orbit', 'order', 'organ', 'other', 'ought', 'outer', 'owner', 'oxide',
  'ozone', 'paint', 'panic', 'paper', 'party', 'pasta', 'patch', 'pause',
  'peace', 'pearl', 'penny', 'perch', 'peril', 'phase', 'phone', 'photo',
  'piano', 'pilot', 'pinch', 'pixel', 'pizza', 'place', 'plain', 'plane',
  'plant', 'plaza', 'plead', 'pluck', 'plumb', 'plume', 'plump', 'plunge',
  'point', 'porch', 'posed', 'power', 'press', 'price', 'pride', 'prime',
  'print', 'prior', 'prize', 'probe', 'prone', 'proof', 'prose', 'proud',
  'prove', 'proxy', 'prune', 'psalm', 'pulse', 'pupil', 'queen', 'query',
  'quest', 'queue', 'quick', 'quiet', 'quota', 'quote', 'radar', 'radio',
  'raise', 'rally', 'ranch', 'range', 'rapid', 'ratio', 'reach', 'ready',
  'realm', 'rebel', 'refer', 'reign', 'relay', 'repay', 'repel', 'reply',
  'resin', 'resto', 'retry', 'ridge', 'right', 'risky', 'rival', 'river',
  'robin', 'robot', 'rocky', 'rouge', 'rough', 'round', 'route', 'rover',
  'royal', 'ruins', 'ruler', 'rusty', 'sadly', 'saint', 'salad', 'sauce',
  'scale', 'scene', 'score', 'scout', 'screw', 'seize', 'sense', 'serve',
  'setup', 'seven', 'shaft', 'shake', 'shall', 'shame', 'shape', 'share',
  'sharp', 'sheen', 'sheep', 'sheer', 'shelf', 'shell', 'shift', 'shine',
  'shirt', 'shock', 'shoot', 'shore', 'short', 'shout', 'shrug', 'sight',
  'sigma', 'silly', 'since', 'sixth', 'sixty', 'sized', 'skill', 'skull',
  'slate', 'slave', 'sleek', 'sleep', 'slice', 'slide', 'slope', 'smart',
  'smell', 'smelt', 'smile', 'smoke', 'solar', 'solve', 'sorry', 'south',
  'space', 'spare', 'spark', 'speak', 'speed', 'spend', 'spice', 'spine',
  'spite', 'split', 'spoon', 'sport', 'spray', 'squad', 'stack', 'staff',
  'stage', 'stain', 'stair', 'stake', 'stale', 'stand', 'stare', 'stark',
  'start', 'state', 'stays', 'steal', 'steel', 'steep', 'steer', 'stern',
  'stick', 'stiff', 'still', 'stock', 'stomp', 'stone', 'stood', 'store',
  'storm', 'story', 'stout', 'strap', 'straw', 'strip', 'stuck', 'study',
  'style', 'sugar', 'suite', 'sunny', 'super', 'surge', 'swamp', 'swarm',
  'swear', 'sweep', 'sweet', 'swept', 'swift', 'swirl', 'sword', 'swore',
  'sworn', 'table', 'taboo', 'taint', 'taste', 'teach', 'tense', 'tenth',
  'terms', 'their', 'theme', 'there', 'thick', 'thing', 'think', 'third',
  'thorn', 'those', 'three', 'threw', 'throw', 'tiger', 'timer', 'tired',
  'titan', 'title', 'toast', 'today', 'token', 'total', 'touch', 'tough',
  'towel', 'tower', 'toxic', 'track', 'trade', 'trail', 'train', 'tramp',
  'trans', 'trash', 'treat', 'trend', 'trial', 'tribe', 'trick', 'tried',
  'troop', 'trout', 'trove', 'truck', 'truly', 'trump', 'trunk', 'trust',
  'truth', 'tumor', 'tuner', 'tweak', 'twice', 'twist', 'tying', 'ultra',
  'uncle', 'under', 'unify', 'union', 'unite', 'unity', 'until', 'upper',
  'upset', 'urban', 'usage', 'usual', 'utter', 'value', 'vault', 'verse',
  'video', 'vigor', 'viral', 'virus', 'visor', 'vista', 'vital', 'vivid',
  'vocal', 'voice', 'voter', 'vying', 'waste', 'watch', 'water', 'weave',
  'wedge', 'weigh', 'weird', 'where', 'which', 'while', 'white', 'whole',
  'whose', 'widen', 'wider', 'woman', 'women', 'world', 'worry', 'worse',
  'worst', 'worth', 'would', 'wound', 'wrist', 'wrote', 'yacht', 'yield',
  'young', 'yours', 'youth', 'zebra',
]
