/**
 * Extended valid-guess list — every word a player is allowed to submit even if
 * it will never be the answer. Swap for the full ~12 000-word list before shipping.
 * The answer list is automatically merged in by useWordle, so no duplicates needed.
 *
 * Contains words of all supported lengths (3–8). useWordle filters by active length.
 */
export const VALID_WORDS: string[] = [
  // ── 3-letter extras ───────────────────────────────────────────────────────
  'ado', 'ago', 'alp', 'amp', 'ant', 'ape', 'apt', 'arc', 'ark', 'asp',
  'ate', 'awe', 'axe', 'aye', 'bee', 'beg', 'bra', 'bye', 'cab', 'cod',
  'cog', 'coo', 'cop', 'cow', 'cry', 'cub', 'dab', 'dam', 'dew', 'die',
  'dim', 'dip', 'doe', 'dry', 'dub', 'due', 'dug', 'dun', 'duo', 'ebb',
  'eel', 'ego', 'elf', 'elk', 'elm', 'emu', 'era', 'eve', 'ewe', 'fad',
  'fed', 'foe', 'fry', 'gel', 'gnu', 'god', 'hew', 'hex', 'hoe', 'hog',
  'hop', 'hub', 'hue', 'imp', 'inn', 'ion', 'ire', 'its', 'jab', 'jag',
  'jot', 'jug', 'keg', 'kin', 'kit', 'lad', 'lag', 'lap', 'lay', 'lea',
  'lei', 'let', 'lie', 'maw', 'mew', 'moo', 'mow', 'nag', 'nil', 'nip',
  'nub', 'nun', 'odd', 'ode', 'off', 'ohm', 'orb', 'our', 'owe', 'pea',
  'peg', 'per', 'phi', 'pox', 'pro', 'pry', 'ram', 'rim', 'rod', 'rut',
  'ski', 'sly', 'spa', 'spy', 'sue', 'sup', 'thy', 'tip', 'tub', 'urn',
  'vim', 'wan', 'wee', 'wig', 'yam', 'yap', 'yin', 'yum', 'zap',

  // ── 4-letter extras ───────────────────────────────────────────────────────
  'abet', 'abut', 'aged', 'agog', 'ahem', 'alms', 'aloe', 'also', 'amok',
  'ankh', 'anus', 'apex', 'aqua', 'aria', 'arid', 'arty', 'ashy', 'atop',
  'avow', 'awry', 'bait', 'bale', 'balk', 'balm', 'bane', 'bard', 'bawd',
  'bawl', 'bead', 'beak', 'bier', 'bile', 'bilk', 'blot', 'boar', 'bode',
  'bosh', 'bray', 'brim', 'brow', 'burp', 'burr', 'calf', 'carp', 'chad',
  'clam', 'clap', 'claw', 'clay', 'clef', 'clod', 'clog', 'colt', 'coma',
  'cozy', 'crag', 'cram', 'crow', 'crud', 'cuff', 'cull', 'daft', 'dais',
  'dale', 'damp', 'dank', 'daze', 'deft', 'dell', 'dike', 'dill', 'ding',
  'dire', 'dirk', 'dolt', 'dote', 'dour', 'dowl', 'drab', 'dram', 'drat',
  'drew', 'drub', 'duel', 'dune', 'dupe', 'earl', 'eely', 'epic', 'erne',
  'faze', 'fern', 'feud', 'fibs', 'fisc', 'fizz', 'flab', 'flan', 'flay',
  'flea', 'fled', 'flew', 'flex', 'flit', 'floe', 'flop', 'flux', 'foal',
  'foil', 'folk', 'fond', 'font', 'furl', 'fuzz', 'gale', 'garb', 'gash',
  'gasp', 'gawk', 'gaze', 'gild', 'gist', 'give', 'glee', 'glen', 'glob',
  'glop', 'glut', 'goad', 'gorge', 'gory', 'gust', 'haft', 'hale', 'halo',
  'hank', 'haze', 'heed', 'helm', 'hemp', 'hilt', 'hind', 'hoax', 'hone',
  'honk', 'hoop', 'hose', 'howl', 'hulk', 'hull', 'hump', 'hunk', 'hurl',
  'ikon', 'imam', 'itch', 'jeer', 'jibe', 'jiff', 'jink', 'jinx', 'jive',
  'jowl', 'kelp', 'kerf', 'kern', 'kink', 'kite', 'knob', 'lair', 'lard',
  'lark', 'lash', 'laud', 'lava', 'laze', 'leek', 'leer', 'levy', 'lewd',
  'lilt', 'limp', 'lisp', 'loft', 'loin', 'lore', 'lout', 'lull', 'lump',
  'lung', 'lurk', 'lute', 'maim', 'malt', 'mare', 'maul', 'meek', 'meld',
  'mend', 'mesa', 'mesh', 'miff', 'mime', 'mire', 'mist', 'mitt', 'mock',
  'moil', 'molt', 'moot', 'mope', 'mort', 'moue', 'moult', 'mourn', 'muck',
  'muds', 'muff', 'mulch', 'mull', 'murk', 'muse', 'musk', 'nape', 'narc',
  'nark', 'nerd', 'newt', 'nimb', 'noel', 'nook', 'nowt', 'null', 'numb',
  'oafs', 'oath', 'oboe', 'ogre', 'omen', 'ooze', 'opus', 'orca', 'oryx',
  'outdo', 'pall', 'pang', 'pant', 'para', 'pare', 'parka', 'parr', 'pave',
  'pawn', 'peal', 'peat', 'peck', 'perm', 'pewit', 'phew', 'pimp', 'plod',
  'plop', 'plow', 'ploy', 'pluck', 'plumb', 'plump', 'plunk', 'pock', 'pomp',
  'pore', 'pout', 'prim', 'prod', 'prom', 'prow', 'puke', 'pulp', 'punt',
  'putt', 'quay', 'quip', 'rack', 'raft', 'rile', 'rime', 'rimy', 'rind',
  'roan', 'romp', 'rook', 'rout', 'rove', 'rowl', 'rube', 'ruin', 'rump',
  'ruse', 'sago', 'sate', 'scam', 'scan', 'scar', 'scud', 'serf', 'shag',
  'shah', 'sham', 'shiv', 'shod', 'shun', 'sill', 'silo', 'silt', 'skew',
  'skid', 'skim', 'skip', 'skit', 'slag', 'slat', 'slav', 'slaw', 'slay',
  'slew', 'sloe', 'slop', 'slot', 'slub', 'slum', 'slur', 'smew', 'smog',
  'smug', 'snag', 'snob', 'snug', 'snog', 'soda', 'soma', 'spud', 'stab',
  'stag', 'stud', 'sump', 'swab', 'swag', 'swam', 'swan', 'swap', 'swat',
  'swum', 'tack', 'tang', 'taut', 'teat', 'temp', 'tend', 'thud', 'thug',
  'tide', 'tiff', 'toil', 'tome', 'tong', 'torq', 'tray', 'trod', 'trot',
  'tuft', 'turd', 'turf', 'tusk', 'twit', 'tyke', 'ugly', 'undo', 'upon',
  'vamp', 'vend', 'vent', 'verb', 'very', 'vice', 'vied', 'view', 'vile',
  'visa', 'volt', 'waft', 'wand', 'wasp', 'weld', 'welt', 'wend', 'whet',
  'whim', 'whip', 'whit', 'whiz', 'wick', 'wilt', 'wisp', 'womb', 'wore',
  'writ', 'yore', 'zeal', 'zest',

  // ── 6-letter extras ───────────────────────────────────────────────────────
  'ablaze', 'abroad', 'absorb', 'accuse', 'adhere', 'adjoin', 'adjure',
  'adsorb', 'afloat', 'afghan', 'afield', 'aflame', 'aghast', 'agreed',
  'alight', 'alpine', 'ambush', 'amiable', 'anklet', 'aplomb', 'appall',
  'ardent', 'armory', 'ascend', 'aspire', 'assail', 'assent', 'astray',
  'attest', 'avatar', 'avenge', 'behold', 'benign', 'bestow', 'bewail',
  'bewray', 'biopsy', 'bisect', 'blotch', 'blouse', 'boggle', 'boldly',
  'bother', 'bounty', 'bridle', 'browse', 'brutal', 'bungle', 'candid',
  'canopy', 'captor', 'catchy', 'cavern', 'cellar', 'census', 'chaste',
  'cheery', 'cherub', 'chilly', 'chroma', 'classy', 'cliche', 'cloaks',
  'cobalt', 'cobble', 'coddle', 'coerce', 'compel', 'comply', 'concur',
  'coping', 'crafty', 'craven', 'crimson', 'crisps', 'crunch', 'cypher',
  'dangle', 'dapper', 'dawdle', 'dazzle', 'debris', 'debunk', 'decode',
  'decoys', 'deface', 'deform', 'degree', 'detach', 'devout', 'divert',
  'dogleg', 'doting', 'dungeon', 'duping', 'earthy', 'embody', 'endure',
  'enfold', 'enjoin', 'ensure', 'entail', 'entwine', 'errant', 'exalts',
  'excite', 'exempt', 'expand', 'exhale', 'facial', 'fading', 'falter',
  'fathom', 'fervid', 'fetish', 'finale', 'fleece', 'flimsy', 'flirty',
  'floral', 'frosty', 'frothy', 'furtive', 'gamble', 'garish', 'garner',
  'girder', 'gravel', 'greedy', 'grimly', 'grovel', 'grudge', 'grumpy',
  'haggle', 'hamper', 'hansom', 'harbor', 'hasten', 'hearty', 'heresy',
  'heroic', 'humbly', 'hustle', 'icicle', 'ignite', 'immense', 'impede',
  'insult', 'invade', 'invoke', 'ironic', 'kindle', 'lavish', 'legacy',
  'lethal', 'likely', 'lively', 'loosen', 'mangle', 'maroon', 'marvel',
  'mellow', 'menace', 'modest', 'molten', 'mortal', 'mortar', 'muster',
  'narrow', 'nimble', 'noble', 'notable', 'nourish', 'oblique', 'obtain',
  'offend', 'oppressor', 'ordeal', 'pander', 'placid', 'pliant', 'plunge',
  'potion', 'primer', 'prompt', 'propel', 'prosper', 'punish', 'purify',
  'radiant', 'rampage', 'ransom', 'ravage', 'ravine', 'recede', 'reclaim',
  'redeem', 'refine', 'reform', 'refute', 'render', 'repent', 'retort',
  'revere', 'revive', 'riddle', 'ripple', 'risque', 'rotate', 'rugged',
  'rumble', 'sadden', 'salute', 'sanity', 'sardine', 'satchel', 'scorch',
  'sedate', 'serene', 'soothe', 'stitch', 'strife', 'stripe', 'subtle',
  'sunken', 'swerve', 'tangle', 'tariff', 'tarnish', 'temper', 'tendon',
  'tether', 'thatch', 'thrive', 'throng', 'topple', 'touchy', 'trance',
  'trudge', 'tumble', 'twinge', 'tyrant', 'unruly', 'uplift', 'utmost',
  'vacant', 'verify', 'vertex', 'vessel', 'vivify', 'vocals', 'waddle',
  'wander', 'warden', 'warble', 'whimsy', 'wither', 'woozy', 'writhe',
  'wraith', 'zealot',

  // ── 7-letter extras ───────────────────────────────────────────────────────
  'abandon', 'ability', 'absence', 'acclaim', 'account', 'accrued', 'acquire',
  'adamant', 'address', 'adopted', 'adverse', 'afflict', 'aggravate', 'agonize',
  'ailment', 'allegiance', 'amplify', 'ancient', 'anxious', 'appoint', 'approve',
  'assault', 'attempt', 'attract', 'auction', 'audible', 'average', 'backing',
  'bailout', 'banking', 'bargain', 'barrier', 'benefit', 'blatant', 'booming',
  'caption', 'caution', 'ceiling', 'circuit', 'citizen', 'clarity', 'classic',
  'climate', 'clouded', 'cluster', 'compile', 'conquer', 'consent', 'consist',
  'console', 'consult', 'corrupt', 'council', 'counsel', 'counter', 'crusade',
  'declare', 'decline', 'devoted', 'dignify', 'dilemma', 'dismiss', 'diverse',
  'enforce', 'enhance', 'excited', 'exclude', 'exhaust', 'explore', 'extreme',
  'fantasy', 'fervent', 'focused', 'frantic', 'furious', 'gateway', 'glowing',
  'graphic', 'genuine', 'grieved', 'harmony', 'hostile', 'hurtful', 'ignores',
  'immerse', 'impulse', 'involve', 'journey', 'justice', 'kinetic', 'license',
  'lighten', 'mandate', 'marshal', 'massive', 'maximal', 'mindful', 'miracle',
  'monitor', 'mournful', 'natural', 'neglect', 'network', 'neutral', 'notable',
  'nucleus', 'nurture', 'obscure', 'offense', 'offhand', 'ongoing', 'organic',
  'passage', 'passive', 'perform', 'persist', 'premise', 'proceed', 'profile',
  'promise', 'prosper', 'pursuit', 'qualify', 'quality', 'radical', 'rapport',
  'reached', 'resolve', 'respond', 'rethink', 'revenge', 'rhythm', 'rigidly',
  'ruthless', 'satisfy', 'savings', 'segment', 'sensing', 'servant', 'serving',
  'sharing', 'shifting', 'skilled', 'solving', 'sorcery', 'squalid', 'startle',
  'stellar', 'stimulate', 'stoic', 'strange', 'succeed', 'summary', 'survival',
  'suspend', 'sustain', 'tactics', 'tolerate', 'torment', 'torture', 'triumph',
  'trivial', 'turbine', 'typical', 'uncover', 'undergo', 'unearth', 'uniform',
  'upgrade', 'utensil', 'utilize', 'vacancy', 'verdict', 'version', 'vibrant',
  'victory', 'violate', 'violent', 'visible', 'warning', 'whereas', 'witness',
  'wording',

  // ── 8-letter extras ───────────────────────────────────────────────────────
  'abstract', 'accurate', 'adequate', 'adjacent', 'admitted', 'adorable',
  'advanced', 'advisory', 'affected', 'affluent', 'analysis', 'analyzed',
  'animated', 'annually', 'apparent', 'approved', 'attached', 'attained',
  'balanced', 'behavior', 'believed', 'belonged', 'borrowed', 'capacity',
  'captured', 'carefree', 'catering', 'changing', 'chemical', 'climbing',
  'coaching', 'competed', 'compiled', 'conflict', 'confused', 'creating',
  'criminal', 'critical', 'crossing', 'darkness', 'defended', 'designed',
  'directed', 'disabled', 'disaster', 'distinct', 'dominant', 'doubtful',
  'dwelling', 'economic', 'eligible', 'embraced', 'emphasis', 'employee',
  'enormous', 'ensuring', 'entering', 'equating', 'eventual', 'evidence',
  'expected', 'explored', 'external', 'fabulous', 'fearless', 'fighting',
  'flagship', 'followed', 'football', 'forceful', 'forcibly', 'formally',
  'fruitful', 'glorious', 'greatest', 'grieving', 'guardian', 'handling',
  'harmless', 'hesitate', 'highland', 'homeless', 'imperial', 'improved',
  'included', 'indicate', 'informed', 'instance', 'intimate', 'invented',
  'isolated', 'labeling', 'likewise', 'limiting', 'listened', 'location',
  'lonesome', 'magnetic', 'manifest', 'maximize', 'medieval', 'minimize',
  'moderate', 'modified', 'navigate', 'negative', 'occupied', 'openness',
  'outbreak', 'overlook', 'parallel', 'peaceful', 'pleasant', 'positive',
  'prepared', 'profound', 'promoted', 'property', 'proposal', 'protocol',
  'realized', 'regarded', 'relevant', 'remained', 'replaced', 'required',
  'resigned', 'resolved', 'resource', 'resulted', 'rotating', 'saturate',
  'scholars', 'selected', 'shortage', 'somebody', 'standing', 'starting',
  'stealthy', 'studying', 'superior', 'survived', 'swimming', 'terminal',
  'thrilled', 'touching', 'tracking', 'training', 'transfer', 'traveled',
  'troubled', 'unstable', 'visiting', 'volcanic', 'wondrous', 'workshop',
  'aahed', 'aalii', 'abaci', 'aback', 'abaft', 'abase', 'abash', 'abate',
  'abbey', 'abbot', 'abeam', 'abele', 'abhor', 'abide', 'abler', 'abode',
  'aboon', 'abore', 'abort', 'abram', 'abray', 'abrin', 'abris', 'absey',
  'absit', 'abuna', 'abune', 'abuts', 'abyes', 'abysm', 'abyss', 'acajou',
  'acari', 'aceta', 'ached', 'acher', 'aches', 'achoo', 'acids', 'acing',
  'acini', 'ackee', 'acmes', 'acned', 'acnes', 'acock', 'acold', 'acorn',
  'acres', 'acred', 'acted', 'actin', 'acton', 'added', 'adder', 'adeem',
  'adhan', 'adieu', 'adios', 'admen', 'adobe', 'adown', 'adoze', 'adred',
  'adsum', 'adust', 'aegis', 'aeons', 'aerie', 'afoot', 'afoul', 'afrit',
  'afros', 'agama', 'agami', 'agape', 'agaric', 'agaze', 'aggro', 'agha',
  'agile', 'aging', 'agism', 'agist', 'aglet', 'aglow', 'agone', 'agons',
  'agony', 'agora', 'agouti', 'agued', 'agues', 'ahem', 'ahull', 'aided',
  'aider', 'aides', 'aioli', 'airer', 'airth', 'aisle', 'aitch', 'ajwan',
  'akela', 'alack', 'alamo', 'alane', 'alang', 'alary', 'alate', 'albee',
  'aleph', 'algae', 'algal', 'algas', 'algid', 'algum', 'alias', 'alibi',
  'allay', 'allee', 'allis', 'allod', 'allot', 'alloy', 'allyl', 'almah',
  'almas', 'almeh', 'almon', 'aloes', 'alow', 'altho', 'alula', 'alway',
  'amass', 'amaze', 'amble', 'ameba', 'amend', 'amice', 'amide', 'amigo',
  'amine', 'amino', 'amiss', 'amity', 'amole', 'among', 'ample', 'amply',
  'ampul', 'amuse', 'anear', 'anent', 'anile', 'anima', 'anime', 'anion',
  'aniso', 'annex', 'annul', 'anode', 'anomy', 'antae', 'antas', 'antes',
  'antsy', 'unwed', 'aorta', 'apage', 'apeak', 'aphid', 'apian', 'apish',
  'apnea', 'apode', 'aport', 'appel', 'arced', 'ardor', 'areic', 'arete',
  'ariel', 'arles', 'armed', 'armet', 'arpen', 'arson', 'artel', 'artsy',
  'arums', 'arvos', 'ascot', 'ashen', 'ashet', 'assay', 'aster', 'astir',
  'atilt', 'atman', 'atoll', 'atomy', 'atone', 'atony', 'atopy', 'attar',
  'attic', 'audio', 'auger', 'aught', 'augur', 'aural', 'aurar', 'auric',
  'auris', 'auxin', 'avast', 'avens', 'avion', 'aviso', 'avows', 'awash',
  'awing', 'awoke', 'axial', 'axile', 'axing', 'axiom', 'babka', 'babel',
  'backs', 'badly', 'baken', 'baler', 'balky', 'bally', 'balms', 'balmy',
  'bandy', 'bards', 'bared', 'barge', 'baric', 'baron', 'barre', 'basso',
  'baste', 'batik', 'baton', 'bayou', 'braid', 'beige', 'belle', 'beryl',
  'bestow', 'betel', 'bevvy', 'bilge', 'binge', 'biome', 'birch', 'blare',
  'bliss', 'bloat', 'bloke', 'blunt', 'blurb', 'blurt', 'boggy', 'bogie',
  'boomy', 'boost', 'boozy', 'borax', 'bossy', 'botch', 'bothy', 'bough',
  'boyar', 'brant', 'brash', 'brawn', 'braze', 'brine', 'brisk', 'broil',
  'brood', 'broth', 'brows', 'brunt', 'bumpy', 'bunny', 'burly', 'bursa',
  'caddy', 'cadet', 'cameo', 'canny', 'canto', 'caper', 'cargo', 'carol',
  'carom', 'catnap', 'caulk', 'cavil', 'cedar', 'chafe', 'champ', 'chant',
  'chaps', 'chard', 'chary', 'chasm', 'chevy', 'chide', 'chime', 'chimp',
  'chips', 'chirp', 'chivy', 'chomp', 'chops', 'chord', 'chose', 'chuck',
  'chump', 'chunk', 'churl', 'churn', 'chute', 'cider', 'cigar', 'cinch',
  'cited', 'clang', 'clank', 'cleat', 'cleft', 'clench', 'cling', 'clink',
  'cloak', 'clops', 'clove', 'clown', 'cluck', 'clump', 'clung', 'cobra',
  'cocoa', 'coils', 'colic', 'color', 'combo', 'comet', 'comfy', 'commix',
  'creep', 'cress', 'crest', 'croon', 'crumb', 'cruse', 'cubic', 'cumin',
  'cupid', 'curly', 'curry', 'cutie', 'daffy', 'daisy', 'dandy', 'dapple',
  'daunt', 'decal', 'decoy', 'defer', 'deity', 'delve', 'demon', 'dense',
  'depot', 'derby', 'detox', 'dingo', 'dirty', 'disco', 'ditzy', 'diver',
  'divot', 'dopey', 'dowdy', 'downy', 'dozen', 'drank', 'drape', 'drawl',
  'droit', 'dross', 'drupe', 'duchy', 'ducky', 'dummy', 'dunce', 'dusky',
  'duvet', 'ebony', 'eclat', 'edict', 'egret', 'elegy', 'elide', 'elude',
  'emery', 'emir', 'enact', 'endow', 'epics', 'equip', 'erase', 'erect',
  'ergot', 'erode', 'ether', 'evoke', 'exert', 'exile', 'exult', 'eyrie',
  'faker', 'farce', 'fated', 'faugh', 'fawn', 'fecal', 'felon', 'femur',
  'feral', 'ferny', 'fetid', 'fetus', 'ficus', 'filed', 'finch', 'fishy',
  'fitly', 'fizzy', 'flail', 'flake', 'flaky', 'flair', 'flare', 'flask',
  'flaw', 'fleck', 'fleet', 'flinch', 'flit', 'floam', 'flock', 'flood',
  'floss', 'flout', 'flown', 'fluff', 'fluky', 'flunk', 'flurry', 'flute',
  'flyby', 'foamy', 'foray', 'forgo', 'forte', 'frail', 'freak', 'freed',
  'frond', 'froth', 'froze', 'frugal', 'fugue', 'furry', 'fuzzy', 'gabby',
  'gavel', 'gaudy', 'gauze', 'gauzy', 'gawky', 'gauze', 'gazer', 'gecko',
  'geeky', 'geyser', 'gimpy', 'girly', 'girth', 'glare', 'glint', 'gloss',
  'glout', 'glove', 'gloze', 'gnarl', 'gnash', 'gnome', 'goner', 'gouge',
  'gourd', 'graft', 'grail', 'graze', 'greed', 'greet', 'grime', 'grimy',
  'gripe', 'grist', 'grizz', 'groin', 'groom', 'grope', 'grout', 'gruff',
  'grume', 'grump', 'grunge', 'guava', 'guile', 'gusto', 'gutsy', 'hammy',
  'haste', 'haunt', 'haven', 'havoc', 'hazel', 'heron', 'hippy', 'hoary',
  'hovel', 'hover', 'hunky', 'hurdy', 'hussy', 'husky', 'imago', 'ingle',
  'ingot', 'inlay', 'inset', 'inter', 'intro', 'irked', 'jaunt', 'jazzy',
  'jiffy', 'jimmy', 'joist', 'jolly', 'joust', 'jowly', 'jumpy', 'juror',
  'kebab', 'kitty', 'knave', 'knurl', 'koala', 'kudos', 'larva', 'lasso',
  'latex', 'lathy', 'laxly', 'lease', 'leech', 'leery', 'lefty', 'leggy',
  'lemma', 'lemon', 'liege', 'lilac', 'lithe', 'llama', 'loamy', 'lofty',
  'loopy', 'lousy', 'lumpy', 'lusty', 'lusus', 'mafia', 'manly', 'manor',
  'mangy', 'matey', 'maxim', 'mealy', 'messy', 'milky', 'mimic', 'minty',
  'mirth', 'moody', 'mopey', 'mossy', 'musty', 'nanny', 'natch', 'natty',
  'nervy', 'newsy', 'niece', 'nippy', 'nitty', 'noddy', 'norma', 'notch',
  'nutty', 'nymph', 'oaken', 'oafish', 'oaken', 'octet', 'odder', 'oddly',
  'oddments', 'odeum', 'onion', 'oomph', 'otter', 'ovoid', 'ovule', 'oxide',
  'paddy', 'palmy', 'pansy', 'panty', 'parry', 'patsy', 'patty', 'peaky',
  'peaty', 'peppy', 'perky', 'petal', 'petty', 'pewit', 'phony', 'piney',
  'pinky', 'pipit', 'tipsy', 'pithy', 'piton', 'pudgy', 'plaid', 'planky',
  'plonk', 'plume', 'plunk', 'pogey', 'pokey', 'poppy', 'preen', 'prick',
  'primp', 'privy', 'prong', 'prowl', 'prude', 'prune', 'pudgy', 'puffy',
  'pulpy', 'puppy', 'purse', 'pushy', 'pygmy', 'quaff', 'qualm', 'quash',
  'quaff', 'quirk', 'quota', 'rabbi', 'rabid', 'radon', 'raspy', 'rayon',
  'reedy', 'retro', 'revel', 'rivet', 'rondo', 'ruddy', 'rugby', 'rumba',
  'rummy', 'saggy', 'sapling', 'satin', 'savvy', 'scald', 'scalp', 'scant',
  'scary', 'scone', 'scoop', 'scamp', 'scrub', 'scrum', 'seedy', 'semen',
  'sentry', 'serum', 'shady', 'shoal', 'shoji', 'showy', 'shrub', 'shrunk',
  'slain', 'slant', 'slosh', 'sloth', 'slunk', 'slurp', 'slush', 'slyly',
  'snack', 'snafu', 'snare', 'snarl', 'sneak', 'sneer', 'snide', 'sniff',
  'snore', 'snort', 'snout', 'snowy', 'snuck', 'snuff', 'soggy', 'sonny',
  'sooty', 'soppy', 'sorry', 'souse', 'spate', 'speck', 'spelt', 'spent',
  'spiry', 'spoon', 'spotty', 'spout', 'sprig', 'spunk', 'spurn', 'spurt',
  'staid', 'steep', 'stony', 'stooge', 'straw', 'strep', 'strew', 'strop',
  'strut', 'stump', 'stung', 'stunt', 'suede', 'sulky', 'sully', 'sunup',
  'surge', 'surly', 'swath', 'sweat', 'swoon', 'swoop', 'syrup', 'tabby',
  'taffy', 'tangy', 'tardy', 'tarry', 'taunt', 'teary', 'tepid', 'terse',
  'theta', 'thong', 'tidal', 'timid', 'tinny', 'tithe', 'torso', 'touchy',
  'toxin', 'tripe', 'tromp', 'troll', 'trove', 'truce', 'truly', 'tubby',
  'tulle', 'tulip', 'tummy', 'tunny', 'turbo', 'turmeric', 'tusky', 'twerp',
  'twill', 'twine', 'twirl', 'twitch', 'unfit', 'unmet', 'unpeg', 'unpin',
  'unrig', 'unsay', 'unset', 'untie', 'uteri', 'uvula', 'vapid', 'vegan',
  'venal', 'veneer', 'verge', 'vest', 'vetch', 'vexed', 'vicar', 'vigil',
  'viper', 'viand', 'vogue', 'voila', 'voile', 'vomit', 'vouch', 'waddy',
  'wafer', 'wagon', 'wacky', 'wally', 'waltz', 'warty', 'whelp', 'witty',
  'wodge', 'woozy', 'wormy', 'wrath', 'wryly', 'yahoo', 'yappy', 'yawl',
  'yearn', 'yeasty', 'yelpy', 'yokel', 'yucky', 'yummy', 'zappy', 'zesty',
  'zilch', 'zingy', 'zippy', 'zomby', 'zonal', 'zonk',
]
